version: 2

models:

    - name: sales
      description : Our sales
      tests:
        - unique:
            column_name: "(orders_id || '-' || products_id)"
            
      columns:
          - name: orders_id
            description : the orders identifier 
            tests : 
            - not_null 

          - name: products_id
            description : the Products identifier 
            tests : 
            - not_null 
          - name: qty
            
          - name: turnover
            description : the turnover generting by sales 
            tests : 
            - not_null 
          - name: purchase_cost
            description : the purchase costs 
            tests : 
            - not_null 
          - name: margin
            description : the revenue margin
            